title: "Aishwar Govil"
email: aishwar99govil@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning and Data Science Enthusiast
baseurl: "/" 
url: "https://AishwarGovil.github.io/" 
github_username:  AishwarGovil

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
